##############################################################################
# Welcome, this is the default configuration file for the Application.
#
# This configuration defines how the program will run.
# The file is written in the "YAML" - format, which is a great style for expressing properties.
#
# In YAML different levels of indentation indicate different levels in the hierarchy of properties.
# Always keep 2 spaces per level and DO NOT USE TABS for indentation
# use '/' as path separator
# paths without leading separator resolve locally to %APPLICATION_HOME%
# alternatively, specify fully qualified path (e.g. C:/Temp/Data)
# Comments are prefixed with '#'
# Blank lines are skipped
##############################################################################

server:
  port: 80

command-receiver:
  commands:
    # each script needs an identifier to be called via the rest interface
    command-id:
      # this is the script that will be executed
      script: "echo script-1-in-the-list"
      # add a delay after script execution before returning the results
      delay: "PT0.25S"
    chain-command:
      delay: "PT2S" #2 seconds delay between the commandos
      script:
        - "echo script-list-1"
        - "echo script-list-2"
        - "echo script-list-3"
